# Default server — fallback для всех без совпадения с доменом
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    ssl_certificate     /etc/nginx/cert/default.crt;
    ssl_certificate_key /etc/nginx/cert/default.key;
    server_name _;
    return 444;
}
