# Cloudflare real IP restore
map $uri $sub_label {
    ~^/sub/(?<label>[A-Za-z0-9_-]+)_[A-Za-z0-9]+\.txt$  "__COUNTRY__ VLESS | $label";
    default                                                "__COUNTRY__ VLESS";
}
